// import { Header } from '@src/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@src/components/ThemeProvider';
import ClientProvider from '@src/components/ClientProvider';
import Header from '@src/components/Header';
import FirebaseAuthProvider from '@src/components/FirebaseAuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClientProvider>
      <html lang="en">
        <body className={inter.className}>
          <FirebaseAuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
          </ThemeProvider>
</FirebaseAuthProvider>
        </body>
      </html>
    </ClientProvider>
  );
}
